/*
Implement helper methods on MissionApiImpl for emitting 
mission-related events to the frontend and wrapping 
any mission event-trigger logic.
*/

use tauri::{AppHandle, Runtime};
use crate::missions::types::MissionsStruct;
use super::{MissionApiImpl, MissionEventTrigger}; 

// We need MissionEventTrigger. This is usually generated by the macro in mod.rs. 
// If it's generated in `mod.rs`, we can import it via `super::MissionEventTrigger`.

impl MissionApiImpl {
    /// Emit state changes to frontend
    /// Should be called after any state modification
    pub fn emit_state_update(
        &self,
        app_handle: &AppHandle<impl Runtime>,
        state: &MissionsStruct,
    ) -> Result<(), String> {
        MissionEventTrigger::new(app_handle.clone())
            .on_updated(state.clone())
            .map_err(|e| e.to_string())
    }
}


